""" to run this script, open the command prompt enter the below line (note python environment here needs to be pre-loaded with argis pro package and licenses):
python "code\generate image labels\python\assign_images_to_blobs.py"
"""

import arcpy
import math

arcpy.env.qualifiedFieldNames = False
arcpy.env.overwriteOutput = True


arcpy.env.workspace = r"[enter gdb name].gdb"
arcpy.env.overwriteOutput = True

#this popdbuff_splitbobs_national.shp shapefile was generated by hand in arcgis pro by creating a feature for each contiguous set of images, and splitting large contiguous urban areas into smaller subsets
#each of these urban areas is referred to as a "blob" throughout the code, because we didn't get into computational economics for our impeccable diction :)
arcpy.MakeFeatureLayer_management(r"data\labels\source files\urban_areas_shapefile\popdbuff_splitblobs_national.shp", "blobs_shp")
arcpy.FeatureClassToFeatureClass_conversion("blobs_shp", r"[enter gdb name].gdb", "blobs")


arcpy.TabulateIntersection_analysis("blobs", "fnum", "image_pts_national_large" ,r"data\labels\generated files\image_intersections\blob_ints_large.csv", "img_id")

arcpy.TabulateIntersection_analysis("blobs", "fnum", "image_pts_national_small" ,r"data\labels\generated files\image_intersections\blob_ints_small.csv", "img_id")

arcpy.TabulateIntersection_analysis("blobs", "fnum", "image_pts_national_mw_highres" ,r"data\labels\generated files\image_intersections\blob_ints_mw_highres.csv", "img_id")


